# Generated by Django 3.2.5 on 2021-07-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='repetition',
            new_name='repetitions',
        ),
    ]
